djangomom/app/urls.py
from django.conf.urls import url

import views

urlpatterns = [
    # Creates new App Obj
    url(r'^create/$',
        views.AppCreateView.as_view(),
        name='create'),
    url(r'^resources_list/(?P<pk>[^/]+)/$',
        views.ResourcesListView.as_view(),
        name='resources_list'),
    # Project deatil or list of app for specific project.
    url(r'^(?P<pk>[^/]+)/$',
        views.ProjectAppListView.as_view(),
        name='index'),
]

djangomom/djangomom/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('project.urls',
        namespace='projects')),
    url(r'^apps/', include('app.urls',
        namespace='apps')),
    url(r'^models/', include('modeller.urls',
        namespace='models')),
    url(r'^account/', include('account.urls',
        namespace='account')),
    url(r'^', include('core.urls',
        namespace='core')),
    url(r'^endpoint/', include('endpoint.urls',
        namespace='endpoint')),
    url(r'^serializer/', include('serializer.urls',
        namespace='serializer')),
]

djangomom/templates/change_password.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>APIMonk</title>

  <!-- Bootstrap core CSS -->

  <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">

  <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">

  <!-- Custom styling plus plugins -->
  <link href="{% static 'css/custom.css' %}"  rel="stylesheet">
  <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}"  rel="stylesheet">


  <script src="{% static 'js/jquery.min.js' %}"></script>

  <!--[if lt IE 9]>
        <script src="../assets/js/ie8-responsive-file-warning.js"></script>
        <![endif]-->

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

</head>

<body style="background:#F7F7F7;">

  <div class="">
    <a class="hiddenanchor" id="toregister"></a>
    <a class="hiddenanchor" id="tologin"></a>

    <div id="wrapper">
      <div id="login" class="animate form">
        <section class="login_content">
          <form  class="form-signin" role="form" id="login_form" action="{% url 'core:change_password' %}" method="post">{% csrf_token %}
            <h1>Password Change</h1>
            <div class="row">
                <div class="col-lg-12">
                    {% if messages %}
                         {% for message in messages %}
                         <div class="alert alert-warning" role="alert">
                          <strong><h5>{{ message }}</h5></strong> 
                        </div>
                         {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <input class="form-control" placeholder="Password" name="password1" type="password" autofocus>
            </div>
            <div class="form-group">
                <input class="form-control" placeholder="Re-Type Password" name="password2" type="password" value="">
            </div>
            <div>
              <button class="btn btn-primary-small " type="submit" value="login">Change password</button>
              <!-- <a class="reset_pass" href="#">Lost your password?</a> -->
            </div>
            <div class="clearfix"></div>
            <div class="separator">
              <div class="clearfix"></div>
              <br />
              <div>
                <h1><i class="fa fa-cloud" style="font-size: 26px;"></i> APIMonk!</h1>

                <p>©2018-19 All Rights Reserved. Privacy and Terms</p>
              </div>
            </div>
          </form>
          <!-- form -->
        </section>
        <!-- content -->
      </div>
    </div>
  </div>

</body>

</html>

djangomom/templates/dashboard.html
{% extends "base/dashboard_base_v_2.html" %}

{% block wrapper %}
</br>
<div class="row">
  <div class="col-lg-12">
    {% if messages %}
         {% for message in messages %}
         <div class="alert alert-success" role="alert">
          <strong>{{ message }}</strong> 
        </div>
         {% endfor %}
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col-lg-8 col-sm-8 col-xsm-8">
    <div class="x_panel">
      <div class="x_title">
        <h2>List of Projects</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li> -->
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      {% if projects %}
      <div class="x_content">
        <table class="table">
          <thead>
            <tr>
              <th>Project</th>
              <th><small> DataBase</small></th>
              <th><small> Host URL</small></th>
              <th><small> Last Update</small></th>
            </tr>
          </thead>
          <tbody>
          {% for project in projects %}
            <tr>
              <th><a href="{% url 'apps:index' project.id %}">{{project | capfirst}}</a></th>
              <td><small> {{project.get_data_base_display}}</small></th>
              <td><small> {{project.host_url}}</small></th>
              <td><small> {{project.updated_at}}</small></th>
            </tr>
          {% endfor%}
          </tbody>
        </table>
      </div>
      {% else %}
      <div class="x_content">
          Hello there! Welcome to Djangomom! Get started Add New project
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

djangomom/templates/signin.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Welcome to API-Factory</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../../../static/signin/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../../../static/signin/css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" >
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <!-- <div class="site-heading">
                        <h1></h1>
                        
                        <span class="subheading"></span>
                    </div>
                    <div class="site-heading">
                        <h4></h4>
                    </div> -->
                </div>
            </div>
        </div>
    </header>
            

        <div class="container">
        <div class="row">
        <div class="col-md-4 ">
            <img src="/static/img/django.png" class="img" height="500" width="500">
            </div>
            <!-- <div class="row"> -->   
            <div class="col-md-4 col-md-offset-2">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Sign In - API-Factory</h3>
                    </div>
                    </br>
                    <div class="col-lg-12">
                        {% if messages %}
                             {% for message in messages %}
                             <div class="alert alert-warning" role="alert">
                              <strong><h5>{{ message }}</h5></strong> 
                            </div>
                             {% endfor %}
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        <form  class="form-signin" role="form" id="login_form" action="{% url 'core:login_user' %}" method="post">{% csrf_token %}
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Username" name="username" type="username" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password" name="password" type="password" value="">
                                </div>
                                <!-- <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div> -->
                                <!-- Change this to a button or input when using this as a form -->
                                <button class="btn btn-primary-small " type="submit" value="login">Sign in</button>
                                <button class="btn btn-primary-small " href="/#contact" target="_blank">Register ?</button>
                                <input type="hidden" name="next" value="{{ next }}" />

                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>


  

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    
                    <p class="copyright text-muted">Copyright &copy; www.greendesignlabs.in 2017-18  <a href="/license/">License</a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="../../../../static/signin/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../../../static/signin/js/bootstrap.min.js"></script>



</body>

</html>