djangomom/app/urls.py
from django.conf.urls import url

import views

urlpatterns = [
    # Creates new App Obj
    url(r'^create/$',
        views.AppCreateView.as_view(),
        name='create'),
    url(r'^resources_list/(?P<pk>[^/]+)/$',
        views.ResourcesListView.as_view(),
        name='resources_list'),
    # Project deatil or list of app for specific project.
    url(r'^(?P<pk>[^/]+)/$',
        views.ProjectAppListView.as_view(),
        name='index'),
]

djangomom/djangomom/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('project.urls',
        namespace='projects')),
    url(r'^apps/', include('app.urls',
        namespace='apps')),
    url(r'^models/', include('modeller.urls',
        namespace='models')),
    url(r'^account/', include('account.urls',
        namespace='account')),
    url(r'^', include('core.urls',
        namespace='core')),
    url(r'^endpoint/', include('endpoint.urls',
        namespace='endpoint')),
    url(r'^serializer/', include('serializer.urls',
        namespace='serializer')),
]

djangomom/modeller/urls.py
from django.conf.urls import url

from .models import *

import views

urlpatterns = [
    # Creates model objs
    url(r'^create/$',
        views.ModelObjectCreateView.as_view(),
        name='create'),
    # Creates model field objs
    url(r'^create_field/$',
        views.ModelFieldCreateView.as_view(),
        name='create_field'),
    # modelobject deatil or list of modelfields for specific modelobject.
    url(r'^detail/(?P<pk>[^/]+)/$',
        views.ModelObjectDetailView.as_view(),
        name='detail'),
    # List of modelobjects for specific app.
    url(r'^(?P<pk>[^/]+)/$',
        views.AppModelObjectListView.as_view(),
        name='index'),
]

djangomom/modeller/models.py
from __future__ import unicode_literals

from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver


from base.models import TimeStamp

import logging
logger = logging.getLogger(__name__)

INHERITOBJ = (
    (0, 'Contact'),
    (1, 'TimeStamp'),
)


class ModelObject(TimeStamp):

    app = models.ForeignKey('app.App')
    name = models.SlugField(max_length=50)

    def __unicode__(self):
        return self.name

    def fields_count(self):
        return self.modelfield_set.count()

    def code_name(self):
        # Return model name in django format EX: poll.Poll
        return '{1}.{0}'.format(self.name.capitalize(), self.app.name_lower)

    def app_code_name(self):
        # Return model name in django format
        # with app uuid prefixed EX: _safkljdkflsadfsf_poll.Poll
        return '{1}.{0}'.format(
            self.name.capitalize(), self.app.app_code_name)

    def unpack(self):
        import ast
        inheritance_list = [INHERITOBJ[int(obj)][1] for obj in ast.literal_eval(self.inherit)]
        return ','.join(inheritance_list)

    class Meta:
        unique_together = ("app", "name")

    def get_default_endpoints(self):
        endpoints = list()
        endpoints.append(
            dict(
                url='{2}/{0}/{1}_list/'.format(
                    self.app.name_lower,
                    self.name.lower(),
                    self.app.project.host_url
                ),
                model_name='{0} GET'.format(self.name.lower())
            )
        )
        endpoints.append(
            dict(
                url='{2}/{0}/{1}_detail/<object_id>'.format(
                    self.app.name_lower,
                    self.name.lower(),
                    self.app.project.host_url
                ),
                model_name='{0} GET'.format(self.name.lower())
            )
        )
        endpoints.append(
            dict(
                url='{2}/{0}/{1}_create/'.format(
                    self.app.name_lower,
                    self.name.lower(),
                    self.app.project.host_url
                ),
                model_name='{0} POST'.format(self.name.lower())
            )
        )
        endpoints.append(
            dict(
                url='{2}/{0}/{1}_update/<object_id>'.format(
                    self.app.name_lower,
                    self.name.lower(),
                    self.app.project.host_url
                ),
                model_name='{0} POST'.format(self.name.lower())
            )
        )
        endpoints.append(
            dict(
                url='{2}/admin/{0}/{1}/'.format(
                    self.app.name_lower,
                    self.name.lower(),
                    self.app.project.host_url
                ),
                model_name='{0} CRUD'.format(self.name.lower())
            )
        )
        return endpoints


FieldTypes = (
#    (1, 'AutoField'),
    (2, 'IntegerField'),
    (3, 'FloatField'),
    (4, 'DateField'),
    (5, 'DateTimeField'),
    (6, 'EmailField'),
    (7, 'TimeField'),
    (8, 'DecimalField'),
    (9, 'CharField'),
    (10, 'SlugField'),
    (11, 'TextField'),
    (12, 'URLField'),
    (13, 'BigIntegerField'),
    (14, 'SmallIntegerField'),
    (15, 'PositiveSmallIntegerField'),
    (16, 'BooleanField'),
    (17, 'ForeignKey'),
    (18, 'ManyToManyField'),
    (19, 'OneToOneField'),
    (20, 'DurationField')
)


class ModelField(TimeStamp):

    model_obj = models.ForeignKey(ModelObject)
    name = models.SlugField(max_length=50)
    field_type = models.IntegerField(
        blank=True, choices=FieldTypes)
    max_length = models.IntegerField(blank=True, null=True)
    default = models.CharField(max_length=50, blank=True, null=True)
    blank = models.BooleanField(default=False)
    null = models.BooleanField(default=True)
    foreign_key = models.CharField(max_length=100, blank=True, null=True)
    many_to_many_key = models.CharField(max_length=50, blank=True, null=True)
    related_name = models.CharField(max_length=50, blank=True, null=True)

    def __unicode__(self):
        return "{0}-{1}".format(self.model_obj, self.name)

    class Meta:
        unique_together = ('model_obj', 'name')


@receiver(post_save, sender=ModelField, dispatch_uid="prepare_app")
def prepare_app(sender, instance, **kwargs):
    instance.model_obj.app.prepare_app()
    import time
    time.sleep(0.5)
    instance.model_obj.app.migrate()
    if instance.model_obj.modelfield_set.count() == 1:
        add_permissions(instance)


def add_permissions(instance):
    import requests
    from django.conf import settings
    url = '{0}/perm/add/'.format(instance.model_obj.app.project.host_url)
    data = {
        'username': instance.model_obj.app.created_by.username,
        'app_label': instance.model_obj.app.name_lower,
        'model': instance.model_obj.name.lower(),
        'SECRET_KEY': settings.SECRET_KEY
    }
    try:
        response = requests.get(url, data)
        if response.status_code != 200:
            logger.critical(
                'Some serious error \
                    while adding perms: Response{0}'.format(
                    response.content))
        else:
            logger.info("Response: {0}".format(response.content))
    except requests.ConnectionError:
        logger.error("ERROR in connecting to secondary server")


QUERYSETTYPE = (
    ('LIST', 'List'),
    ('SINGLE', 'Single'),
)


class QuerySet(TimeStamp):

    name = models.CharField(max_length=100)
    model = models.ForeignKey('modeller.ModelObject', null=True)
    queryset_type = models.CharField(max_length=10, choices=QUERYSETTYPE)
    order_paramater = models.ForeignKey(
        'modeller.ModelField', null=True, blank=True)
    reverse = models.BooleanField(default=False)
    get_all = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name

    def query_method(self):
        if self.get_all:
            return 'objects.all()'
        elif self.queryset_type == 'LIST':
            filter_string = 'objects.'
            for query_filter in self.querysetfilter_set.all():
                filter_string += query_filter.get_filter_string()
            return filter_string
        else:
            return 'objects.get()'


FILTEROPERATION = (
    ('gte', 'Greater Than'),
    ('lte', 'Less Than'),
    ('contains', 'Contains'),
    ('exact', 'exact'),
    ('isnull', 'Is Null'),
    ('startswith', 'Starts With'),
    ('endswith', 'Ends With'),
)

FILTERTYPE = (
    ('exclude', "Exclude"),
    ('filter', "Include")
)


class QuerySetFilter(TimeStamp):

    filter_type = models.CharField(max_length=10, choices=FILTERTYPE)
    queryset = models.ForeignKey('modeller.QuerySet')
    paramater = models.ForeignKey('modeller.ModelField')
    operation = models.CharField(
        max_length=10, choices=FILTEROPERATION, null=True, blank=True)
    filter_value = models.CharField(max_length=5000)

    def get_filter_string(self):
        if self.operation:
            return '{0}({1}__{2}="{3}")'.format(
                self.filter_type,
                self.paramater.name,
                self.operation,
                self.filter_value
            )
        else:
            return '{0}({1}="{2}")'.format(
                self.filter_type,
                self.paramater.name,
                self.filter_value
            )

djangomom/modeller/forms.py
from django import forms

from .models import ModelObject, ModelField, INHERITOBJ

import logging
logger = logging.getLogger(__name__)


class ModelObjectForm(forms.ModelForm):
    inherit = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=INHERITOBJ, required=False
    )

    class Meta:
        model = ModelObject
        fields = '__all__'


class ModelFieldForm(forms.ModelForm):
    # foreign_key = forms.ChoiceField(choices=options, required=False)
    foreign_key = forms.ChoiceField(required=False)
    many_to_many_key = forms.ChoiceField(required=False)

    class Meta:
        model = ModelField
        exclude = ('null',)

    def __init__(self, *args, **kwargs):
        from django.forms.widgets import HiddenInput
        user = kwargs.pop('user')
        super(ModelFieldForm, self).__init__(*args, **kwargs)
        self.fields['model_obj'].widget = HiddenInput()
        self.fields['model_obj'].value = "New Field name"
        if not user:
            logger.critical("User not provided")
        options = [(model_obj.code_name(), model_obj.code_name()) for model_obj in ModelObject.objects.filter(app__created_by=user)]
        options.insert(0, ('', 'Select'))
        self.fields['foreign_key'].choices = options
        self.fields['many_to_many_key'].choices = options

    def clean(self):
        cleaned_data = super(ModelFieldForm, self).clean()
        field_type = cleaned_data.get("field_type")
        max_length = cleaned_data.get("max_length")

        if field_type in (11, 9, 10) and max_length is None:
            msg = "Char, Slug and TextField need max_length defined"
            self.add_error('max_length', msg)

djangomom/modeller/views.py
from base.views import (
    GenericSelfRedirection, GenericModalCreateView)
from base.mixin import GeneralContextMixin
from base.v2.generic_data_grid_view import GenericDataTableView

from models import ModelObject, ModelField
from forms import ModelObjectForm, ModelFieldForm


class AppModelObjectListView(GeneralContextMixin, GenericDataTableView):

    model = ModelObject
    template_name = "modeller/index.html"
    list_display = [
        'name',
        'created_at',
        'updated_at',
    ]
    title = 'Data Store'
    sub_title = 'Manage you data models'
    detail_page = 'models:detail'

    def get_queryset(self, **kwargs):
        return ModelObject.objects.filter(app=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super(
            AppModelObjectListView, self).get_context_data(**kwargs)
        context['form'] = ModelObjectForm()
        context['app'] = self.kwargs.get('pk')
        return context


class ModelObjectDetailView(GeneralContextMixin, GenericDataTableView):

    model = ModelField
    template_name = "modeller/detail.html"
    list_display = [
        'name',
        'get_field_type_display',
        'null',
        'blank',
        'created_at',
        'updated_at',
    ]
    title = 'List Fields'
    sub_title = 'Build your data store'
    date_range = False

    def get_queryset(self, **kwargs):
        return ModelField.objects.filter(model_obj=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super(
            ModelObjectDetailView, self).get_context_data(**kwargs)
        context['form'] = ModelFieldForm(user=self.request.user)
        context['model_obj_id'] = self.kwargs.get('pk')
        return context


class ModelObjectCreateView(GenericSelfRedirection):

    form_class = ModelObjectForm
    object_name = 'Transaction'
    url_pattern_list = ['models', 'detail']

    def get_error_url(self):
        return '/models/{0}'.format(self.request.POST['app'])

    def get_error_message(self, form):
        return "Sorry unable to create new DataStore. DataStore {0}".format(
            form.errors.as_text())

    def get_success_message(self, form):
        return "Great new DataStore {0} is created. Lets add fields or columns for you DataStore".format(form.instance.name)


class ModelFieldCreateView(GenericModalCreateView):

    form_class = ModelFieldForm
    object_name = 'Field'

    def get_success_url(self):
        return '/models/detail/{0}'.format(self.request.POST['model_obj_id'])

    def form_init(self, request, *args, **kwargs):
        data = request.POST.copy()
        data['model_obj'] = self.request.POST.get('model_obj_id')
        form = self.form_class(data, user=request.user)
        return self.form_check(form, *args, **kwargs)

    # def form_valid(self, form):
    #     instance = form.instance
    #     instance.model_obj = ModelObject.objects.get(
    #         pk=self.request.POST.get('model_obj'))
    #     return super(ModelFieldCreateView, self).form_valid(form)

    def get_error_message(self, form):
        return "Sorry unable to create new Field. {0} ".format(
            form.errors.as_text())

    def get_success_message(self, form):
        return "Great new Field {0} is created.".format(
            form.instance.name,
        )

djangomom/modeller/templates/modeller/detail.html
{% extends "base/dashboard_base_v_2.html" %}
{% load crispy_forms_tags %}
{% block wrapper %}
<br>
<div class="row">
  <div class="col-lg-12">
    {% if messages %}
         {% for message in messages %}
         <div class="alert alert-success" role="alert">
          <strong>{{ message }}</strong> 
        </div>
         {% endfor %}
    {% endif %}
  </div>
</div>
<button class="btn btn-primary" data-toggle="modal" data-target="#addapp">Add Field</button>
<!-- Modal -->
<div class="modal fade" id="addapp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add Field</h4>
      </div>
      <div class="modal-body">
        <form role='form' action="{% url 'models:create_field' %}" method="post">{% csrf_token %}
        <div>
          <input type="text" hidden="" value="{{model_obj_id}}" name="model_obj_id" id="model_obj_id">
          {{form | crispy}}
        </div>
      </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button class="btn btn-primary" >Add</button>
        </div>
      </div>
  </div>
</div>
</form>
<!-- Modal End -->
{% include "base/generic_data_grid_table.html" %}

<script src="../../../static/js/jquery-2.0.2.js"></script>

<script type="text/javascript">
  function reSetFields(){
    $('#id_related_name').css({"display" : "none"});
    $('label[for="id_related_name"]').hide();
    $('#id_foreign_key').css({"display" : "none"});
    $('label[for="id_foreign_key"]').hide();
    $('#id_many_to_many_key').css({"display" : "none"});
    $('label[for="id_many_to_many_key"]').hide();
    $('#id_max_length').css({"display" : "none"});
    $('label[for="id_max_length"]').hide();
    $('#id_max_digits').css({"display" : "none"});
    $('label[for="id_max_digits"]').hide();
    $('#id_decimal_places').css({"display" : "none"});
    $('label[for="id_decimal_places"]').hide();
    $('#id_choices').css({"display" : "none"});
    $('label[for="id_choices"]').hide();
    $("p").hide(".help-block");
  }
  $( document ).ready(function() {
    reSetFields();
});
  $('#id_field_type').change(function() {
        reSetFields();
        if ($("#id_field_type :selected").val() == 17){
            $('#id_foreign_key').css({"display" : "block"});
            $('label[for="id_foreign_key"]').show();
            $('#id_related_name').css({"display" : "block"});
            $('label[for="id_related_name"]').show();
        }
        else if($("#id_field_type :selected").val() == 18){
            $('#id_many_to_many_key').css({"display" : "block"});
            $('label[for="id_many_to_many_key"]').show();
            $('#id_related_name').css({"display" : "block"});
            $('label[for="id_related_name"]').show();
        }
        else if($("#id_field_type :selected").val() == 11 || $("#id_field_type :selected").val() == 10 || $("#id_field_type :selected").val() == 6){
            $('#id_max_length').css({"display" : "block"});
            $('label[for="id_max_length"]').show();
        }
        else if($("#id_field_type :selected").val() == 8){
            $('#id_decimal_places').css({"display" : "block"});
            $('label[for="id_decimal_places"]').show();
            $("#id_decimal_places").attr('required',true);
            $('#id_max_digits').css({"display" : "block"});
            $('label[for="id_max_digits"]').show();
            $("#id_max_digits").attr('required',true);
        }
        else if($("#id_field_type :selected").val() == 9 ){
            $('#id_choices').css({"display" : "block"});
            $('label[for="id_choices"]').show();
            $("p").show(".help-block");
            $('#id_max_length').css({"display" : "block"});
            $('label[for="id_max_length"]').show();
        }
        else if($("#id_field_type :selected").val() == 2 ){
            $('#id_choices').css({"display" : "block"});
            $('label[for="id_choices"]').show();
            $("p").show(".help-block");
        }
  });
</script>
{% endblock %}

djangomom/modeller/templates/modeller/index.html
{% extends "base/dashboard_base_v_2.html" %}
{% load crispy_forms_tags %}
{% block wrapper %}
<br>
<div class="row">
  <div class="col-lg-12">
    {% if messages %}
         {% for message in messages %}
         <div class="alert alert-success" role="alert">
          <strong>{{ message }}</strong> 
        </div>
         {% endfor %}
    {% endif %}
  </div>
</div>
<button class="btn btn-primary" data-toggle="modal" data-target="#transactionmodal">Add Data Store</button>

<!--  Transation Modal -->
<div class="modal fade" id="transactionmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add Data Store</h4>
      </div>
      <div class="modal-body">
        <form role='form' action="{% url 'models:create' %}" method="post">{% csrf_token %}
        <div>
          <input type="text" hidden="" name="app" id="id_app" value="{{app}}">
        </div>
          <label for="name" class="col-2 col-form-label">Data Store Name</label>
          <input class="form-control" type="text" name="name" id="id_name">
      </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" >Create</button>
        </div>
      </div>
  </div>
</div>
</form>
<!-- Modal End -->
{% include "base/generic_data_grid_table.html" %}
{% endblock %}